from OrangeHRMData._BaseLocalizationClass import _BaseNoLocalizationClass


class HTMLAttributes(_BaseNoLocalizationClass):
    accept_attr = "accept"  # Specifies the types of files that the server accepts
    accept_charset_attr = "accept-charset"  # Specifies the character encodings that are to be used for the form
    # submission
    accesskey_attr = "accesskey"  # Defines a keyboard shortcut to activate or focus on the element
    action_attr = "action"  # Specifies the URL where the form data should be submitted
    align_attr = "align"  # Specifies the alignment of an element according to surrounding elements
    allow_attr = "allow"  # Specifies a feature policy for the <iframe> element
    alt_attr = "alt"  # Defines alternative text for images
    async_attr = "async"  # Specifies that the script will be executed asynchronously as soon as it is available
    autocapitalize_attr = "autocapitalize"  # Controls whether the text input should be automatically capitalized
    autocomplete_attr = "autocomplete"  # Specifies whether a form should have autocomplete enabled
    autoplay_attr = "autoplay"  # Specifies that the audio or video will start playing as soon as it is ready
    background_attr = "background"  # Sets the background color or image for an element
    bgcolor_attr = "bgcolor"  # Specifies the background color for a table cell
    border_attr = "border"  # Specifies the width of the border of an element
    buffered_attr = "buffered"  # Contains the time range of already buffered media
    capture_attr = "capture"  # Specifies which camera to use for capturing video or an image
    charset_attr = "charset"  # Specifies the character encoding used in the submitted form data
    checked_attr = "checked"  # Specifies that an input element should be pre-selected when the page loads
    cite_attr = "cite"  # Specifies a URL where the source of the quoted content can be found
    class_attr = "class"  # Specifies one or more class names for an element
    color_attr = "color"  # Specifies the text color of an element
    cols_attr = "cols"  # Specifies the visible width of a text area
    colspan_attr = "colspan"  # Specifies the number of columns a table cell should span
    content_attr = "content"  # Provides metadata about the document for search engines and social media platforms
    contenteditable_attr = "contenteditable"  # Specifies whether the content of an element is editable or not
    contextmenu_attr = "contextmenu"  # Specifies a context menu for an element
    controls_attr = "controls"  # Specifies that audio or video controls should be displayed
    coords_attr = "coords"  # Specifies the coordinates of the hot spot region in an image map
    crossorigin_attr = "crossorigin"  # Allows images from another domain to be used in the <canvas> element
    csp_attr = "Experimental"  # Defines a Content Security Policy for the resource
    data_attr = "data"  # Used to store custom data private to the page or application
    data_asterisk_attr = "data-*"  # Used to store custom data private to the page or application with a specific name
    datetime_attr = "datetime"  # Specifies the date and time for the element
    decoding_attr = "decoding"  # Specifies how the browser should load and decode the image
    default_attr = "default"  # Specifies that a track should be enabled unless the user's preferences indicate
    # otherwise
    defer_attr = "defer"  # Specifies that the script should be executed after the page has been parsed
    dir_attr = "dir"  # Specifies the text direction for the content in an element
    dirname_attr = "dirname"  # Specifies the name of the directory that the server can use to process the form data
    disabled_attr = "disabled"  # Specifies that an input element should be disabled
    download_attr = "download"  # Specifies that the target will be downloaded when a user clicks on the hyperlink
    draggable_attr = "draggable"  # Specifies whether an element is draggable or not
    enctype_attr = "enctype"  # Specifies how the form data should be encoded when submitting it to the server
    enterkeyhint_attr = "enterkeyhint"  # Specifies what action label (or icon) to present for the enter key on
    # virtual keyboards
    for_attr = "for"  # Specifies which form element a label is bound to
    form_attr = "form"  # Specifies the form the element belongs to
    formaction_attr = "formaction"  # Specifies the URL where the form data should be submitted
    formenctype_attr = "formenctype"  # Specifies how the form data should be encoded when submitting it to the server
    formmethod_attr = "formmethod"  # Specifies the HTTP method used to submit the form data
    formnovalidate_attr = "formnovalidate"  # Specifies that the form should not be validated when submitted
    formtarget_attr = "formtarget"  # Specifies where to display the response after submitting the form
    headers_attr = "headers"  # Specifies a space-separated list of header cells that are associated with the current
    # cell
    height_attr = "height"  # Specifies the height of an element
    hidden_attr = "hidden"  # Specifies that an element is not yet, or is no longer, relevant
    high_attr = "high"  # Specifies the high value of a gauge
    href_attr = "href"  # Specifies the URL of the linked resource
    hreflang_attr = "hreflang"  # Specifies the language of the linked resource
    http_equiv_attr = "http-equiv"  # Provides an HTTP header for the information/value of the content attribute
    id_attr = "id"  # Specifies a unique id for an element
    integrity_attr = "integrity"  # Specifies the integrity value of the linked resource
    intrinsicsize_attr = "intrinsicsize"  # Specifies the intrinsic size of the image in pixels
    inputmode_attr = "inputmode"  # Specifies what kind of input mechanism would be most helpful for users entering
    # content into the form control
    ismap_attr = "ismap"  # Specifies that an area should be part of a server-side image map
    itemprop_attr = "itemprop"  # Specifies the name of a property in the item
    kind_attr = "kind"  # Specifies the kind of text track
    label_attr = "label"  # Specifies a user-readable title or caption for an element
    lang_attr = "lang"  # Specifies the primary language for the content in an element
    language_attr = "language"  # Specifies the scripting language of the embedded code
    loading_attr = "loading"  # Specifies how the browser should load the external resource
    list_attr = "list"  # Refers to a <data list> element that contains pre-defined options for an <input> element
    loop_attr = "loop"  # Specifies that the audio or video will start over again, every time it is finished
    low_attr = "low"  # Specifies the low value of a gauge
    manifest_attr = "manifest"  # Specifies the address of the document's cache manifest
    max_attr = "max"  # Specifies the maximum value of an input element
    maxlength_attr = "maxlength"  # Specifies the maximum number of characters allowed in an input element
    minlength_attr = "minlength"  # Specifies the minimum number of characters required in an input element
    media_attr = "media"  # Specifies the media types for which the styles are intended
    method_attr = "method"  # Specifies the HTTP method used to submit the form data
    min_attr = "min"  # Specifies the minimum value of an input element
    multiple_attr = "multiple"  # Specifies that a user can enter more than one value in an input element
    muted_attr = "muted"  # Specifies that the audio output of the video should be muted
    name_attr = "name"  # Specifies the name of an element
    novalidate_attr = "novalidate"  # Specifies that a form should not be validated when submitted
    open_attr = "open"  # Specifies that the details should be visible (open) to the user
    optimum_attr = "optimum"  # Specifies the optimal value for a gauge
    pattern_attr = "pattern"  # Specifies a regular expression that the input element's value is checked against
    ping_attr = "ping"  # Specifies a space-separated list of URLs to be notified if the user follows the hyperlink
    placeholder_attr = "placeholder"  # Specifies a short hint that describes the expected value of an input element
    playsinline_attr = "playsinline"  # Specifies that the audio or video should not play on full screen mode
    poster_attr = "poster"  # Specifies an image to be shown while the video is downloading, or until the user hits
    # the play button.
    preload_attr = "preload"  # Specifies if and how the author thinks the audio or video should be loaded
    readonly_attr = "readonly"  # Specifies that an input element is read-only
    referrerpolicy_attr = "referrerpolicy"  # Specifies which referrer information should be included with requests made
    rel_attr = "rel"  # Specifies the relationship between the current document and the linked resource
    required_attr = "required"  # Specifies that an input element must be filled out before submitting the form
    reversed_attr = "reversed"  # Specifies that the list order should be descending
    role_attr = "role"  # Defines a role for an element
    rows_attr = "rows"  # Specifies the visible number of lines in a text area
    rowspan_attr = "rowspan"  # Specifies the number of rows a table cell should span
    sandbox_attr = "sandbox"  # Enables an extra set of restrictions for the content in an <iframe>
    scope_attr = "scope"  # Specifies whether a header cell is a header for a column, row, or group of columns or rows
    scoped_attr = "scoped"  # Specifies that the styles only apply to this element's parent and its child elements
    selected_attr = "selected"  # Specifies that an option should be pre-selected when the page loads
    shape_attr = "shape"  # Specifies the shape of the area in an image map
    size_attr = "size"  # Specifies the width of an input element
    sizes_attr = "sizes"  # Specifies the size of the linked resource
    slot_attr = "slot"  # Specifies the name of the shadow DOM slot the element is inserted in
    span_attr = "span"  # Specifies the number of columns a <col> element should span
    spellcheck_attr = "spellcheck"  # Specifies whether the element is to have its spelling and grammar checked or not
    src_attr = "src"  # Specifies the URL of the media file
    srcdoc_attr = "srcdoc"  # Specifies the HTML content of the page to show in the <iframe>
    srclang_attr = "srclang"  # Specifies the language of the text track
    srcset_attr = "srcset"  # A list of one or more URLs to image files, each URL separated by a comma
    start_attr = "start"  # Specifies the start value of a gauge
    step_attr = "step"  # Specifies the legal number intervals for an input element
    style_attr = "style"  # Specifies inline CSS styles for an element
    summary_attr = "summary"  # Specifies a summary of the content of a table
    tabindex_attr = "tabindex"  # Specifies the tab order of an element
    target_attr = "target"  # Specifies where to open the linked document
    title_attr = "title"  # Specifies extra information about an element
    translate_attr = "translate"  # Specifies whether the content of an element should be translated or not
    type_attr = "type"  # Specifies the type of element
    usemap_attr = "usemap"  # Specifies an image as a client-side image map
    value_attr = "value"  # Specifies the initial value of an input element
    width_attr = "width"  # Specifies the width of an element
    wrap_attr = "wrap"  # Specifies how the text in a text area is to be wrapped when submitted in a form
