name: Enforce Branch Naming Convention

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  enforce-naming-convention:
    runs-on: ubuntu-latest

    steps:
      - name: Check Branch Naming
        run: |
          branch_name=$(echo ${{ github.event.pull_request.head.ref }})

          if [[ ! "$branch_name" =~ ^test_.*$ ]]; then
            echo "error: Branch name must start with 'test_'."
            exit 1
          fi
