name: Python Test

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.12.1

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: pytest

    - name: Generate Test Report
      run: |
        pytest --junitxml=test-results/junit.xml

    - name: Upload Test Report
      uses: actions/upload-artifact@v2
      with:
        name: test-results
        path: test-results